### ISSUE TITLE
Follow rules of open source licence

### ISSUE THREAD

**Issue by sestegra** [kawal7415/excel_it#2]
As mentioned in MIT licence (see [LICENCE](https://github.com/sestegra/spreadsheet_decoder/blob/master/LICENSE)), you are freely allowed to copy the source code of the [spreadsheet_decoder](https://github.com/sestegra/spreadsheet_decoder) project. It's why I like to develop open source projects.

Nevertheless, you should include the licence of the spreadsheet_decoder project: see
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

Thank you to @shliama to pointing me out your fork.

**Comment by kawal7415** [comment]
Sorry bro I'm new to open source.

I will include the MIT license now.

**Comment by sestegra** [comment]
No problems, I suggest as well to put your name in your licence.

```
   Copyright [yyyy] [name of copyright owner]
```

**Comment by kawal7415** [comment]
I had included the MIT licence, Thanks bro for guiding me and correcting me.

I am actively developing it and the next will be spanned rows and column feature coming out within a week.

**Comment by sestegra** [comment]
Just for my understanding, why don't you contribute to spreadsheet_decoder project instead of creating a new similar project ?

**Comment by kawal7415** [comment]
Firstly I wanted to contribute but as I told u that I am new to github so I wanna do some tweaks and edits and play with git and all.
